greeting:
  message: "hello"



quarkus:
  http:
    access-log:
      exclude-pattern: \/q\/.*
      enabled: true
  log:
    level: INFO
    category:
      "org.apache.http":
        level: INFO
      "net.dslab.slack.api.http": DEBUG
  micrometer:
    binder:
      http-server:
        max-uri-tags: 250
    binder-enabled-default: true
