greeting:
  message: "hello"



quarkus:
  http:
    access-log:
      enabled: true
  log:
    category:
      "org.apache.http":
        level: DEBUG
  micrometer:
    binder:
      http-server:
        max-uri-tags: 250
    binder-enabled-default: true
